<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->
 <?php
  if (!is_array($this->urlParams)) $this->urlParams = array();
 ?>
<?php if ($this->pageCount): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
 de <?php echo $this->totalItemCount; ?>
 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first) + $this->urlParams); ?>">
    Primera
  </a> |
<?php else: ?>
  <span class="disabled">Primera</span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous) + $this->urlParams); ?>">
    &lt; Anterior
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Anterior</span> |
<?php endif; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next) + $this->urlParams); ?>">
    Siguiente &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Siguiente &gt;</span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last) + $this->urlParams); ?>">
    Ultima
  </a>
<?php else: ?>
  <span class="disabled">Ultima</span>
<?php endif; ?>
 
</div>
<?php endif; ?>