<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="http://yui.yahooapis.com/2.8.1/build/reset/reset-min.css" media="screen" rel="stylesheet" type="text/css" />

    <style>
    html {background:url("/img/new/bgbody.png") repeat-y scroll center center #000200;height:100%;}
        body {
font-family:Arial;
font-size:62.5%;height:100%;
        }
        #wrapper {height:100%;
margin:0 auto;
overflow:hidden;
position:relative;
width:760px;}
#header {background-color:#37301D;
height:80px;}
#contenido {font-size:12px;
overflow:hidden;
padding:4px 0 30px;}
        #menu {
overflow:hidden;}
        #menu ul {margin:0 auto;
overflow:hidden;
width:939px;}
        #menu ul li {background:transparent url(/img/new/tab.png) no-repeat scroll center center;
display:inline-block;
height:25px;
line-height:25px;
margin:0 2px;
text-align:center;
width:150px;}
        #menu ul li a {color:#FFFFFF;
font-size:12px;
font-weight:bold;
text-decoration:none;}
#menu ul li a:hover {text-decoration:underline;}

.mobline {background:url("/img/new/barra.png") repeat-x scroll 0 0 transparent;
height:17px;
margin-bottom:6px;}
#submenu ul {}
#submenu ul li {border-right:2px solid #FFFFFF;
float:left;
padding:0 5px;}
#submenu ul li a{color:#000000;
font-size:12px;
text-decoration:none;}

#col_left {float:left;
margin-left:5px;
padding:3px;
width:194px;}
#col_center {float:left;
margin:0 5px;
padding:3px;
width:539px;}
#col_right {background-color:#EFECE0;
float:left;
margin-right:5px;
padding:3px;
width:177px;}

#border {}

ul#recursos  {overflow:hidden;}
ul#recursos li {float:left;
padding:4px 0;
text-align:center;
width:25%;}
p#time {float:right;
margin-right:10px;}

h3 {background-color:#5A5037;
color:#F1DF94;
font-size:12px;
font-weight:bold;
height:20px;
line-height:20px;
margin:3px 0;
padding-left:5px;
text-align:center;}

#col_center p {text-align: center;}
table {width: 100%;text-align: center;}
table td {padding:3px;}

.col50 td {width: 50%;}
#buildings {border-bottom:2px solid #6E0000;
margin-bottom:3px;
padding:3px;
text-align:center;}
#footer {
bottom:0;
position:absolute;
width:100%;
}
#footer .mobline {margin-bottom:0;}
#copyright {background-color:#5A5037;
color:#F1DF94;
font-size:11px;
font-weight:bold;
height:25px;
line-height:25px;
text-align:center;}

ul#main_menu {}
ul#main_menu li span {color:#B4A56D;
float:left;
font-size:11px;
font-weight:bold;
margin-right:20px;
padding-left:7px;}
ul#main_menu li {background:url("/img/new/bgmenu.png") no-repeat scroll 0 0 transparent;
height:30px;
line-height:30px;
margin-bottom:3px;
margin-right:20px;
width:197px;}
ul#main_menu li a {color:#F1DF94;
font-family:arial;
font-size:11px;
font-weight:bold;
text-decoration:none;
text-transform:uppercase;}
ul#main_menu li a:hover {text-decoration:underline;}
h1 {}
    </style>
</head>
<body>
<div id="wrapper">
    <div id="header"><h1>TheMobChallenge</h1</div>
    <div class="mobline"></div>
    <!--<div id="menu">
        Inicio
    Mis Edificios (habitaciones+edificios+recursos)
    Mis Tropas (reclutamiento + seguridad+misiones)
    Mis Entrenamientos (entrenamiento)
    Mi Familia (familias)
    Mapa
    Buscar
    Mensajes
    Clasificacion
    Arbol tecnologico
        <ul>
            <li><a href="">Inicio</a></li>
            <li><a href="">Mis Edificios</a></li>
            <li><a href="">Mis Tropas</a></li>
            <li><a href="">Mis Entrenamientos</a></li>
            <li><a href="">Mi Familia</a></li>
            <li><a href="">Mapa</a></li>
            <li><a href="">Mensajes</a></li>
            <li><a href="">Clasificacion</a></li>
            <li><a href="">Arbol tecnologico</a></li>
        </ul>
    </div>-->

    <!--<div id="submenu">
    <ul>
        <li><a href="">Mis Habitaciones</a></li>
        <li><a href="">Mis Edificios</a></li>
        <li><a href="">Mis Recursos</a></li>
    </ul>
    <p id="time">Mon, 23.08.2010 - 17:07:08</p>
    </div>-->
    <div id="contenido">
      <div>

        <div id="col_left">

        <ul id="main_menu">
            <li><span>001.</span><a href="">Inicio</a></li>
            <li><span>002.</span><a href="">Mis Edificios</a></li>
            <li><span>003.</span><a href="">Mis Tropas</a></li>
            <li><span>004.</span><a href="">Mis Entrenamientos</a></li>
            <li><span>005.</span><a href="">Mi Familia</a></li>
            <li><span>006.</span><a href="">Mapa</a></li>
            <li><span>007.</span><a href="">Mensajes</a></li>
            <li><span>008.</span><a href="">Clasificacion</a></li>
            <li><span>009.</span><a href="">Arbol tecnologico</a></li>
        </ul>

            <!--<form id="buildings">
                <select><option value="25:25:25">25:25:25</option></select>
            </form>
            <br /><p><a href="">Mis Mensajes (2 nuevos)</a></p><br />
            <form>
                <input type="text" size="20" value="Buscar..." />
                <input type="submit" value="Go!" />
            </form>-->

        </div>
        <div id="col_center">

        <ul id="recursos">
            <li>757.593 <img src="/img/new/R1K.gif" alt="Armas" title="Armas" /></li>
            <li>757.593 <img src="/img/new/R2K.gif" alt="Municion" title="Municion" /></li>
            <li>757.593 <img src="/img/new/R3K.gif" alt="Alcohol" title="Alcohol" /></li>
            <li>757.593 <img src="/img/new/R4K.gif" alt="Dolar" title="Dolar" /></li>
        </ul>

        <h3>Tropas</h3>
        <p>Ninguna unidad.</p>

        <h3>Habitaciones</h3>
        <table class="col50">
        <tr><td>01:16:02</td><td>Contrabando (4) Edificio 25:25:17</td></tr>
        <tr><td>01:07:30</td><td>Oficina de El Jefe (3) Edificio 25:25:16</td></tr>
        </table>

        <h3>Entrenamiento</h3>
        <table class="col50">
        <tr><td>04:04:54</td><td>Espionaje (4) Edificio 25:25:17</td></tr>
        </table>

        <h3>Puntos</h3>
        <table class="col50">
        <tr><td>Cantidad Edificios</td><td>2</td></tr>
        <tr><td>Puntos Edificios</td><td>1.568</td></tr>
        <tr><td>Puntos Entrenamiento</td><td>224</td></tr>
        <tr><td>Puntos Tropas</td><td>1.154</td></tr>
        <tr><td>Total Puntos</td><td>2.946</td></tr>
        <tr><td>Poder de Ataque</td><td><a href="">99%</a></td></tr>
        </table>

        </div>
        <!--<div id="col_right">
        <h3>Novedades en la ciudad</h3>
        <p>Guerras activas: 3</p>
        <p>Guerras declaradas hoy: <a href="">2</a></p>
        <p>Ataques de hoy: 1.532</p>
        <p>Mejor batalla: <a href="">Yo vs. Vos</a></p>
        </div> -->


      </div>
    </div>

    <div id="footer">
    <div class="mobline"></div>
    <p id="copyright">Copyright ©TheMobChallenge, 2010.</p>
    </div>
</div>
</body>
</html>