<?php

echo $this->contentBox()->open("Arbol Tecnologico");
echo "<table class='techTree'><tr><td class='c'>".$this->t("Habitacion")."</td><td class='c'>".$this->t("Requisitos")." (".$this->t("Nivel").")</td></tr>";
foreach (Mob_Loader::getHabitaciones() as $obj) {
  $class = $this->getJugador()->getEdificioActual()->cumpleRequisitosHab($obj) ? "imgTechOk" : "imgTechError";
  echo "<tr><th><div class='bgImgTech'><img src='".Mob_Server::getStaticUrl()."img/hab/".$obj->getImagen()."' class='$class'/></div><a class='ajax' href='/mob/habitaciones/ver?v=".$obj->getNombreBdd()."'>".$obj->getNombre()."</a></th>";
  $requisitos = $obj->getRequisitos();
  if (empty($requisitos)) {
    echo "<th>-</th>";
  } else {
    echo "<th>";
    foreach ($requisitos as $req => $nivel) {
      $class = $this->getJugador()->getEdificioActual()->getHabitacion($req)->getNivel() >= $nivel ? "levelTechOk" : "levelTechError";
      $req = Mob_Loader::getHabitacion($req);
      echo "<a class='ajax' href='/mob/habitaciones/ver?v=".$req->getNombreBdd()."'>".$req->getNombre()."</a> <span class='$class'>($nivel)<span><br />";
    }
    echo "</th>";
  }
  echo "</tr>";
}
echo "</table>";
echo $this->contentBox()->close();